### ISSUE TITLE
关于模型训练时长的咨询

### ISSUE THREAD

**Issue by KingRicardo** [ShusenTang/WriteLikeYou#3]
唐先生您好~，感谢您的出色工作。我看您论文里面有提到在1080ti上跑一个epoch需要10个小时，想问下用您提供的代码总共跑多少个epoch比较合适呢？我看您代码里num_steps设的是100万，batchsize是128，训练数据大概是300万，跑完num_steps个ite（43个epoch）大概需要17天，这时间似乎有点太长了，希望您能推荐一个比较合适的num_steps大小。

**Comment by Cydiater** [comment]
Hi, I've tried training locally with my Tesla P-100 and `batch_size = 256`. The model got converged in about 12 hours. Note that you need to pre-train the content encoder and style encoder.

**Comment by KingRicardo** [comment]
> Hi, I've tried training locally with my Tesla P-100 and `batch_size = 256`. The model got converged in about 12 hours. Note that you need to pre-train the content encoder and style encoder.

Thanks for your reply~😀
